### ISSUE TITLE
Add pre-commit hook for running linter

### ISSUE THREAD

**Issue by robbieaverill** [SeequentEvo/evo-data-converters#38]
We can also add a hook to strip Jupyter notebook outputs, as we do in the evo-python-sdk repo: https://github.com/SeequentEvo/evo-python-sdk/blob/main/.pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.1 # keep in sync with pyproject.toml
    hooks:
      - id: ruff
        name: Run linter
      - id: ruff-format
        name: Run formatter
        args: ["--check"]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip outputs from Jupyter notebooks
```
